# Generated by Django 4.2.11 on 2025-12-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_supplier_phone_supplier_mobile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasebill',
            unique_together={('supplier', 'bill_number')},
        ),
    ]
